# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: stream-service-web
  namespace: go-app
spec:
  selector:
    app: stream-service-web
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---

